# Default initial positions for hv_bot's ros2_control fake system

initial_positions:
  base_prismatic_torso: 0
  elbow_joint: 0
  finger_joint: 0
  gripper_joint: 0
  lower_arm_joint: 0
  middle_left_wheel_joint: 0
  middle_right_wheel_joint: 0
  shoulder_joint: 0
  upper_arm_joint: 0
  wrist_joint: 0