# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller
    - base_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - base_prismatic_torso
      - shoulder_joint
      - upper_arm_joint
      - elbow_joint
      - lower_arm_joint
      - wrist_joint
      - gripper_joint
    action_ns: follow_joint_trajectory
    default: true
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - finger_joint
    action_ns: follow_joint_trajectory
    default: true
  base_controller:
    type: FollowJointTrajectory
    joints:
      - middle_left_wheel_joint
      - middle_right_wheel_joint
    action_ns: follow_joint_trajectory
    default: true