controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - base_prismatic_torso
      - shoulder_joint
      - upper_arm_joint
      - elbow_joint
      - lower_arm_joint
      - wrist_joint
      - gripper_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joints:
      - finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity