<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

        <!-- STEREO CAMERA -->

        <link name="stereo_camera">

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.07 0.3 0.09"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="file://$(find hv_bot_arm)/meshes/kinect/d415.dae"/>
                </geometry>
                <material name="black"/>
            </visual>

            <inertial>
                <mass value="0.01"/>
                <xacro:box_inertia m="0.01" x="0.07" y="0.3" z = "0.09"/>
            </inertial>

        </link>

        <joint name="stereo_camera_joint" type="fixed">
            <origin rpy="0 0 0" xyz="${chassis_length/2} 0 ${chassis_height/7}"/>
            <parent link="base_link"/>
            <child link="stereo_camera"/>
        </joint>

        <link name="stereo_camera_optical"/>

        <joint name="stereo_camera_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
            <parent link="stereo_camera"/>
            <child link="stereo_camera_optical"/>
        </joint>



        <gazebo reference="stereo_camera">
            <sensor type="camera" name="right">
                <update_rate>10.0</update_rate>
                <always_on>true</always_on>
                <gz_frame_id>stereo_camera_optical</gz_frame_id>
                <pose>0 -0.12 0 0 0 0</pose>
                <topic>stereo_camera/right/image_raw</topic>
                <camera_info_topic>stereo_camera/right/camera_info</camera_info_topic>
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>1024</width>
                    <height>1024</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.3</near>
                    <far>20</far>
                </clip>
            </sensor>

            <sensor type="camera" name="left">
                <topic>stereo_camera/left/image_raw</topic>
                <update_rate>10.0</update_rate>
                <always_on>true</always_on>
                <gz_frame_id>stereo_camera_optical</gz_frame_id>
                <camera_info_topic>stereo_camera/left/camera_info</camera_info_topic>
                <pose>0 0 0 0 0 0</pose>
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>1024</width>
                    <height>1024</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.3</near>
                    <far>20</far>
                </clip>
            </sensor>
        </gazebo>
</robot>