<?xml version="1.0"?>
<robot name="hv_arm" xmlns:xacro="http://www.ros.org/wiki/xacro"> <xacro:property name="chassis_length" value="0.650"/>


    <xacro:property name="chassis_width" value="0.600"/>
    <xacro:property name="chassis_height" value="0.200"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.027"/>
    <xacro:property name="wheel_thickness" value="0.021"/>
    <xacro:property name="wheel_mass" value="0.15"/>
    <xacro:property name="wheel_offset_x" value="0.30"/>
    <xacro:property name="wheel_offset_y" value="0.2200"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.05"/>
    <xacro:property name="caster_wheel_mass" value="0.055"/>
    <xacro:property name="caster_wheel_offset_x" value="0.1"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

</robot>